version: '3'

services:
  service:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      -  3000:3000

  website:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 5173:8080
    depends_on:
     - service